- docker/build-release.sh
- docker/dev.Dockerfile
- docker/prod.Dockerfile
I'm not sure if this is the best way.
Internally, our build servers frequently get `toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit` because from the outside world, they look like the same IP. We work around that by having a private registry and get containers to build by pulling their base images from that.
There are two ways to support this:
- Overwrite/supply to dockerfile (w/ arg)
- Change the daemon.json for docker to have our private registry as a mirror
I don't particular like the latter as that introduces a hard to notice side effect.. Say private repo has a base image that when builds it works, but the public dockerhub image when used as a base image fails. This would …
> Allow overriding the docker base repository

- gst-plugin-pravega/Cargo.lock
```
KEYCLOAK_SERVICE_ACCOUNT_FILE="/home/luis/keycloak1.json"
PRAVEGA_CONTROLLER_URI="tls://pravega-controller.kubespray.nautilus-platform-dev.com:443"
PRAVEGA_SCOPE="rungpu"
pravega_client_tls_cert_path="/etc/ssl/certs/ca-certificates.crt"
./scripts/videotestsrc-to-pravega-live.sh
```
test for 1 hour, no issue occurs.
> update pravega-rust-client for the keycloak auth renew fix

- apps/src/bin/rtsp-camera-simulator.rs
- gst-plugin-pravega/src/counting_reader.rs
- gst-plugin-pravega/src/counting_writer.rs
- gst-plugin-pravega/src/lib.rs
- gst-plugin-pravega/src/pravegasink/imp.rs
- gst-plugin-pravega/src/pravegasrc/imp.rs
- gst-plugin-pravega/src/seekable_byte_stream_writer.rs
- gst-plugin-pravega/src/utils.rs
- pravega-video/src/index.rs
- pravega-video/src/timestamp.rs
General enhancements:
- Improve logging
- Replace unwrap with returned errors
- No longer allow timestamp 0 in index
pravegasrc:
- Fix deadlock and incorrect seeking behavior
- Add CountingReader to prevent buffer flush when getting current position
- Add offset, offset_end properties to buffers for debugging
pravegasink:
- Add timestamp-mode=tai
- Add SeekableByteStreamWriter and CountingWriter
> Fix deadlock and incorrect seeking behavior in pravegasrc

- gst-plugin-pravega/src/counting_reader.rs
- gst-plugin-pravega/src/counting_writer.rs
- gst-plugin-pravega/src/pravegasink/imp.rs
- gst-plugin-pravega/src/seekable_byte_stream_writer.rs
- gst-plugin-pravega/src/seekable_take.rs
This fixes timestamps produced by tsdemux when reading a stream produced by two invocations of pravegasink.
This PR also fixes some compiler warnings.
> pravegasink: set discontinuity flag on first buffer

- gst-plugin-pravega/src/pravegasink/imp.rs
- gst-plugin-pravega/src/pravegasrc/imp.rs
- scripts/mp4-test5.sh
- scripts/pravega-to-screen-docker.sh
- scripts/pravega-to-screen.sh
- scripts/pravega-to-speaker-split.sh
- scripts/pravega-video-player.sh
- Set segment start time to allow playback with sync=true.
- Change default start-mode to earliest.
- Remove obsolete start-pts-at-zero property.
> pravegasrc: Set segment start time to allow playback with sync=true

- docker/docker/build-gstreamer/compile
- docker/docker/build-gstreamer/install-dependencies
Applied fixes from https://github.com/restreamio/docker-gstreamer/commit/ea80e076230a6f5ea1332573438564b5abbf037a.
> docker: Remove GL dependency to avoid error with missing xdg-shell-client-protocol.h

- Cargo.lock
- deepstream/pravega_protocol_adapter/Cargo.toml
- deepstream/pravega_protocol_adapter/src/lib.rs
1. change connection_str to accept controller_uri (tcp://addr:port or tls://addr:port).
2. put fixed-routing-key and keycloak-file property setting in the config file.
```
[message-broker]
keycloak-file = /home/ubuntu/keycloak1.json
fixed-routing-key = foo
```
to verify:
checkout https://github.com/pravega/gstreamer-pravega/tree/NPS-8613-rewrite-integration-test in the deepsteam pod.
```
cd ./gstreamer-pravega/deepstream/pravega_protocol_adapter 
make test
```
> enabled auth and tls for pravega adaptor

- docker/docker/build-gstreamer/download
Download the Gstreamer repositories in parallel; checkout sequentially.
On my computer and internet connection, doing them sequentially takes 91s. Doing them in parallel is 31s (most is I/O waiting).
"Free" easy speed boost.
> Download in parallel

- docker/build-release.sh
- docker/pravega.Dockerfile
This PR includes various improvements to the the main Dockerfile.
1. Rename pravega-dev.Dockerfile to pravega.Dockerfile since this is no longer just for development.
2. Building of dev and prod images can be disabled with env vars.
3. Always pull the base Ubuntu image unless PULL_BASE=0.
4. Rename stage "base" to "debug-prod-compile".
5. Cargo chef prepare now copies specific directories instead of all files.
> Optimize Dockerfile

- scripts/test-integration.sh
- scripts/test-unit.sh
Not having `--locked --release` in the test means that when building in a container that only builds w/ `--locked --release` means that everything will be recompiled.
I thought about putting it behind a flag but I don't see much utility. If one did have a failing test and wanted the debug build, they could individually run the test on the commandline.
> cargo test with locked & release

- scripts/test-integration.sh
Environment variable (JUNIT_OUTPUT) that is zero to output in the normal format or non-zero to output the results in junit format.
> Toggle to export integration test results to junit format

- scripts/test-integration.sh
This is to save us from odd errors later on where Pravega won't launch (missing Java 11) or we can't inspect if Pravega is running (missing netstat, ss, or grep).
I wrote this in the rust code originally but it was ugly. I feel doing it early in the short shell code tidier.
> Check prereqs before integration tests

- docker/pravega.Dockerfile
- pravega-video-server/src/main.rs
- scripts/pravega-video-server.sh
- Rename parameters for pravega-video-server and accept parameters through env vars.
- Change Dockerfile to place pravega-video-server binary in /usr/local/bin so that it is in the path.
> pravega-video-server: Accept parameters through env vars

- pravega-video-server/src/main.rs
In another channel Claudio and I talked about this.
From a security prospective, it is better to have one or more of the following:
- The user view the player directly (and perhaps we enhance the webplayer with more features)
- Let other apps that want video to go through the API on their backend
- Iframe the video player
CORs has some limitation such as browsers not allowing CORs for localhost.
> Remove cors workaround

- k8s/charts/rtsp-camera-to-pravega/values.yaml
- python_apps/rtsp-camera-to-pravega.py
To minimize code invasion, just add the env param to disable log buffer.
To test:
```
helm install rtsp-camera-to-pravega-1 ./gstreamer-pravega/k8s/charts/rtsp-camera-to-pravega -n luis --set image.repository=devops-repo.isus.emc.com:8116/nautilus/gstreamer:luis,global.camera.address=10.243.54.95,global.camera.user=admin,global.camera.password=password,global.camera.rtspPort=8554,global.pravega.stream=pipeline512m,healthCheck.enabled=true,healthCheck.idleSeconds=30,appParameters.CAMERA_PATH="/cam/realmonitor?width=640&height=480",appParameters.GST_DEBUG="WARNING",appParameters.PRAVEGA_RETENTION_POLICY_TYPE=bytes,appParameters.PRAVEGA_RETENTION_BYTES=536870912
```
> disable python log buffer so that log flushes immediately after logging

- deepstream/deepstream-dev-pod.Dockerfile
1. Add tools of netcat (nc), curl, ping, and dig
2. Add libs of python3-opencv, python3-numpy, libgstrtspserver-1.0-0, gstreamer1.0-rtsp, libgirepository1.0-dev, gobject-introspection, gir1.2-gst-rtsp-server-1.0 that is needed by the python examples
> add tools and libs for the deepstream dev pod

- pravega-docker/docker-compose.yml
- pravega-docker/up.sh
Option to not use a local volume in pravega-docker/up.sh. Saves a "sudo" password typing.
On a scale of 1-10, where 7 is "I think this really should go in", this is a 3.
> Optional local volume for pravega up

- Cargo.lock
- apps/Cargo.toml
- apps/src/bin/pravega_event_test1.rs
- apps/src/bin/pravega_event_test2.rs
- deepstream/pravega_protocol_adapter/Cargo.toml
- deepstream/pravega_protocol_adapter/src/lib.rs
- gst-plugin-pravega/Cargo.toml
- gst-plugin-pravega/src/pravegasink/imp.rs
- gst-plugin-pravega/src/pravegasrc/imp.rs
- integration-test/Cargo.toml
- pravega-video-server/Cargo.toml
- pravega-video/Cargo.toml
- pravega-video/src/utils.rs
1. Upgrade gstreamer-pravega to latest Pravega Rust client 6614df550bd286e3d1867022c3f235836c6cc278
2. Update GStreamer plugins to pass Keycloak credentials via API 
Verified by running camera recorder pipeline and playing with pravega video server and check retention policy work. 
The lastest image build: devops-repo.isus.emc.com:8116/nautilus/gstreamer:luis
> upgrade to the lastst pravega rust client

- scripts/test-integration.sh
Before this PR, any lines logged to stdout were not displayed when JUNIT_OUTPUT=1. This PR ensures that stdout and stderr output are displayed. It also ensures that the exit code from `cargo test` is returned by `test-integration.sh`.
> test-integration.sh: Ensure that stdout and stderr are output when cargo2junit is used

- Cargo.lock
- apps/Cargo.toml
- apps/src/bin/pravega-tools.rs
- apps/src/bin/pravega_event_test1.rs
- apps/src/bin/pravega_retention_checker.rs
- deepstream/pravega_protocol_adapter/Cargo.toml
- gst-plugin-pravega/Cargo.toml
- gst-plugin-pravega/src/pravegasink/imp.rs
- gst-plugin-pravega/src/pravegasrc/imp.rs
- integration-test/Cargo.toml
- integration-test/src/utils.rs
- pravega-video-server/Cargo.toml
- pravega-video-server/src/main.rs
- pravega-video/Cargo.toml
This Pravega client update includes a breaking change to the create_byte_reader and create_byte_writer APIs. Segment number is no longer used.
> Update Pravega client to c3b9268

- gst-plugin-pravega/src/timestampcvt/imp.rs
- python_apps/rtsp-camera-to-pravega.py
Some RTSP cameras set timestamps unreliably. This PR makes the camera recording more robust by setting the default timestamp source to the local clock. In case PTS still goes backward, it changes the minimum frame interval from 1 ms to 15 ms so that the frame rate is reasonable.
> Improve robustness of timestamp handling in rtsp-camera-to-pravega

- apps/src/bin/pravega_event_test1.rs
- apps/src/bin/pravega_event_test2.rs
- gst-plugin-pravega/src/pravegasink/imp.rs
- gst-plugin-pravega/src/pravegasrc/imp.rs
- pravega-docker/docker-compose.yml
- pravega-video-server/src/main.rs
- pravega-video/src/utils.rs
This does the following:
- Add a tag to streams we create for video. The stream tag will be "video"
- List Streams API in the Pravega Video Server only lists streams with a video tag (note, the player will still play any stream, regardless on whether it has the tag or not)
- A new List Scopes API in Pravega Video Server
> Use Video Tags

- scripts/test-integration.sh
Before this change, the following integration-test.log would cause a panic in cargo2junit.
```
[2021-07-28T22:30:55.910Z] Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.{ "type": "test", "name": "pravegasrc_tests::test::test_pravegasrc_start_mode_timestamp_max", "event": "ok", "exec_time": 0.540514278 }
```
This occurred because cargo2junit did not detect the JSON object because it was not alone in the line. This PR adds a grep statement to extract the JSON from anywhere in the line.
> test-integration.sh: Handle case when cargo test result JSON is on same line as application output

- Cargo.lock
- apps/Cargo.toml
- deepstream/pravega_protocol_adapter/Cargo.toml
- gst-plugin-pravega/Cargo.toml
- integration-test/Cargo.toml
- pravega-video-server/Cargo.toml
- pravega-video/Cargo.toml
- scripts/videotestsrc-to-pravega-eaglemonk.sh
- scripts/videotestsrc-to-pravega-keycloak.sh
This updates the Pravega client to https://github.com/pravega/pravega-client-rust/commit/c42d55af935d8a7bf1c3460ba2a13fc280691613.
> Fix Keycloak TLS cert validation to use OS trust store

- pravega-video-server/src/main.rs
Reverts pravega/gstreamer-pravega#109 that fails due to a Rust compile error. Investigation is in progress.
> Revert "Check for Needed Static Files"

- deepstream/python_apps/deepstream-pravega-demos/pravega-to-object-detection-to-pravega.py
- gst-plugin-pravega/src/timestampcvt/imp.rs
Default camera recorder behavior is to use mp4 containers. This PR pravega-to-object-detection-to-pravega have the same default.
> pravega-to-object-detection-to-pravega: Change output container format from mpegts to mp4

- .gitignore
- gst-plugin-pravega/src/pravegasrc/imp.rs
- gst-plugin-pravega/src/pravegatc/imp.rs
- integration-test/src/failure_recovery_tests.rs
To make failure recovery more robust, this PR updates **pravegatc** and **pravegasrc**. If pipeline recovery is attempted more than once from the same PTS, it is assumed that the input stream is defective, and subsequent recovery attempts will skip over increasing amounts of data. 
The start-mode parameter of **pravegasrc** now has two variations of timestamp values. The "timestamp-exact" enum causes the segment to start at the specified time. The "timestamp" enum causes the segment to start at the time in the index record. During recovery, **pravegatc** will use "timestamp-exact" mode first, but if that fails and recovery starts from the same location again, then "timestamp" mode will be used with an increasing timestamp.
> [STRM-11119] pravegatc failure recovery now skips potential input stream errors

- docker/pravega.Dockerfile
The ubuntu base image sets the user as 'root'. This is undesirable and causes some issues when deploying on some environments like OpenShift.
This change creates a user for the container and sets the final container to run as it.
> Use non-root user for container

- docker/build-gstreamer/compile
This is required because meson now throws an error on unknown options.
See https://github.com/mesonbuild/meson/issues/932. 
Camera Recorder Pipeline and Pravega Video Server have been tested successfully.
> Change docker/build-gstreamer/compile to specify exact build options required for each project

- python_apps/rtsp-camera-to-pravega.py
Enable camera recorder pipeline to read rtsp over SSL and write into pravega
> Enable secure rtsp for camera recorder pipeline

- gst-plugin-pravega/src/pravegasink/imp.rs
- gst-plugin-pravega/src/pravegasrc/imp.rs
- gst-plugin-pravega/src/timestampcvt/imp.rs
- gst-plugin-pravega/tests/timestampcvt.rs
- integration-test/src/file_import_tests.rs
- integration-test/src/lib.rs
- python_apps/rtsp-camera-to-pravega.py
- python_apps/video_file_to_pravega.py
Element `timestampcvt` parameter `input-timestamp-mode` now has option `start-at-fixed-time` to make the PTS of the first buffer equal to a fixed time. This is useful when importing video from a file source.
Unit and integration tests have been updated.
Note that the option `relative` has been renamed to `start-at-current-time`.
```
scripts/test-all.sh
...
test-all.sh: All tests completed successfully.
```
> Add option to timestampcvt to start timestamp at fixed time

- gst-plugin-pravega/src/timestampcvt/imp.rs
With this change, buffers with DTS, such as those with H.264 video, can be offset correctly.
> timestampcvt now applies offset to DTS

- Cargo.lock
- deepstream/deepstream-dev-pod.Dockerfile
- deepstream/pravega-deepstream.Dockerfile
- docker/build-release.sh
- docker/install-prod-dependencies
- docker/pravega.Dockerfile
- gst-plugin-pravega/src/timestampcvt/imp.rs
- gst-plugin-pravega/tests/timestampcvt.rs
Updating the base image to `ubuntu:22.04` to get the latest security fixes:
- updated the base ubuntu image
- updated openssl-related rust dependencies
- updated prod dependencies to match the ones shipped with ubuntu:22.04
- updated the key to pull the deepstream image (as the key got rotated recently)
- fixed the integration test to work with the updated dependencies
Testing: integration tests passed
> Update base image to ubuntu:22.04

- README.md
- apps/src/bin/pravega_event_dumper.rs
- gst-plugin-pravega/tests/timestampcvt.rs
- pravega-video-server/src/main.rs
- pravega-video/src/event_serde.rs
- pravega-video/src/index.rs
- scripts/pravega-event-dumper.sh
1. some gstreamer element like h264parse may add discont flag to I frames which would play blue gaps for now.
For indexes whose gap from last index are less than the target duration, simply ignore the discont flag before we could figure out why discont flag was set to mitigate the blue gap issue temporarily.
2. integration test could execute with latest rust binaries now
> Fix blue gap issue
