- pravega-video/src/timestamp.rs
> pravega-video: Add operators to PravegaTimestamp. Add TimeDelta.

- python_apps/rtsp-camera-to-pravega.py
> rtsp-camera-recorder: warn on queue overrun

- Cargo.lock
Not sure how exactly it happened but this lock file got coblled in a previous merge.
> Cargo lock commited

- gst-plugin-pravega/src/pravegasink/imp.rs
- pravega-video/src/event_serde.rs
> pravegasink: Fragment buffers greater than 8 MiB

- gst-plugin-pravega/src/pravegasink/imp.rs
- gst-plugin-pravega/src/pravegasrc/imp.rs
> pravegasink/src: Fix handling of empty keycloak-file

- gst-plugin-pravega/src/fragmp4pay/imp.rs
- gst-plugin-pravega/src/fragmp4pay/mod.rs
- gst-plugin-pravega/src/lib.rs
- gst-plugin-pravega/src/timestampcvt/imp.rs
- gst-plugin-pravega/src/timestampcvt/mod.rs
> Add new elements fragmp4pay, timestampcvt

- python_apps/rtsp-camera-to-pravega.py
> rtsp-camera-to-pravega.py: Now supports MP4 container format

- pravega-video/src/timestamp.rs
> pravega-video: Add functions to TimeDelta

- docker/pravega-dev.Dockerfile
Also fixed a typo. Not sure if it has any effect.
> RUST_JOBS arg in right place.

- Cargo.lock
- apps/Cargo.toml
- apps/src/bin/pravega-tools.rs
- apps/src/bin/pravega_event_test1.rs
- apps/src/bin/pravega_event_test2.rs
- apps/src/bin/pravega_table_test1.rs
- deepstream/pravega_protocol_adapter/Cargo.toml
- deepstream/pravega_protocol_adapter/src/lib.rs
- gst-plugin-pravega/Cargo.toml
- gst-plugin-pravega/src/pravegasink/imp.rs
- gst-plugin-pravega/src/pravegasrc/imp.rs
- gst-plugin-pravega/src/seekable_byte_stream_writer.rs
- integration-test/Cargo.toml
- integration-test/src/utils.rs
- pravega-video-server/Cargo.toml
- pravega-video-server/src/main.rs
- pravega-video/Cargo.toml
- pravega-video/src/event_serde.rs
- pravega-video/src/utils.rs
Bump to latest rust client.
Names shifted to become more concise (ex. ByteStreamReader -> ByteReader).
Tests succeed.
> Bump Rust Client

- pravega-video/src/utils.rs
> pravega-video: Set Pravega max_connections_in_pool to 0 to work around connection pooling bug

- python_apps/rtsp-camera-to-pravega.py
> rtsp-camera-to-pravega.py: Add option to set pravegasink buffer size

- apps/src/bin/pravega-video-player.rs
> pravega-video-player: Change query period to 4 sec

- deepstream/ca-certificates/README.txt
- deepstream/docker-build.sh
- deepstream/pravega-deepstream.Dockerfile
This PR changes the Deepstream Dockerfile similarly to https://github.com/pravega/gstreamer-pravega/pull/58.
> deepstream: Optimize Dockerfile

- pravega-docker/docker-compose.yml
> Decrease bookkeeper disk usage

- scripts/rtsp-camera-to-pravega-python.sh
> Change log file in rtsp-camera-to-pravega-python.sh

- deepstream/pravega-deepstream.Dockerfile
> Add RUST_JOBS to pravega-deepstream.Dockerfile

- k8s/charts/rtsp-camera-simulator/.helmignore
- k8s/charts/rtsp-camera-simulator/Chart.yaml
- k8s/charts/rtsp-camera-simulator/templates/deployment.yaml
- k8s/charts/rtsp-camera-simulator/templates/service.yaml
- k8s/charts/rtsp-camera-simulator/values.yaml
Signed-off-by: Luis Liu <luis_liu@dell.com>
> add rtsp simulator chart

- gst-plugin-pravega/src/pravegasink/imp.rs
- gst-plugin-pravega/src/seekable_byte_stream_writer.rs
- python_apps/rtsp-camera-to-pravega.py
For this pr only cover the implementation of retention of days. 
Will have a seperated PR for the retention of bytes and daysAndBytes.
> Add retention policy to GStreamer Plugin pravegasink

- k8s/charts/rtsp-camera-to-pravega/templates/deployment.yaml
- k8s/charts/rtsp-camera-to-pravega/values.yaml
> rtsp-camera-to-pravega Helm chart now writes logs to a PVC

- gst-plugin-pravega/src/pravegasink/imp.rs
- gst-plugin-pravega/src/pravegasrc/imp.rs
return error when empty controller and stream is set.
Signed-off-by: Luis Liu <luis_liu@dell.com>
> Handle empty controller and stream

- deepstream/pravega_protocol_adapter/src/lib.rs
Running the command below:
GST_PLUGIN_PATH=./gstreamer-pravega/target/debug:${GST_PLUGIN_PATH} pravega_client_tls_cert_path=/etc/ssl/certs/ca-certificates.crt ./gstreamer-pravega/deepstream/python_apps/deepstream-pravega-demos/pravega-to-object-detection-to-pravega.py --allow-create-scope false --input-stream examples/camera-claudio-05 --gst-debug "WARNING" --pravega-controller-uri "tls://pravega-controller.kubespray.nautilus-platform-dev.com:443" --keycloak-service-account-file /home/ubuntu/keycloak_examples.json --log-level 10 --msgapi-config-file /home/ubuntu/msgapi-config.txt --output-metadata-stream examples/luis-metadata-01 --proto-lib ./gstreamer-pravega/target/debug/libnvds_pravega_proto.so
Verify by:
https://jupyterhub.examples.kubespray.nautilus-platform-dev.com/user/desdp/lab/tr …
> pravega_protocol_adapter: Fix memory corruption when writing to Pravega

- python_apps/rtsp-camera-to-pravega.py
update rtsp-camera-to-pravega.py args name to be compatible with camera recorder pipeline pod
> update rtsp-camera-to-pravega.py args

- apps/src/bin/pravega_retention_checker.rs
- scripts/pravega-retention-checker.sh
```
PRAVEGA_SCOPE=luis PRAVEGA_STREAM=pipeline512m PRAVEGA_CONTROLLER_URI=tcp://10.243.52.38:9090 KEYCLOAK_SERVICE_ACCOUNT_FILE=/home/luis/keycloak_pks_luis.json CHECK_PERIOD=10 ./scripts/pravega-retention-checker.sh
```
test result:
> add retention check to verify retention policy

- Cargo.lock
- apps/Cargo.toml
- apps/src/bin/pravega_event_test1.rs
- apps/src/bin/pravega_event_test2.rs
- deepstream/pravega_protocol_adapter/Cargo.toml
- deepstream/pravega_protocol_adapter/src/lib.rs
- gst-plugin-pravega/Cargo.toml
- gst-plugin-pravega/src/pravegasink/imp.rs
- gst-plugin-pravega/src/pravegasrc/imp.rs
- integration-test/Cargo.toml
- pravega-video-server/Cargo.toml
- pravega-video/Cargo.toml
- pravega-video/src/utils.rs
- python_apps/rtsp-camera-to-pravega.py
set update_at to an earlier time to make sure is_healthy marked false at startup
> mark health check failure at startup

- deepstream/deepstream-dev-pod.Dockerfile
> add netstat and ip command

- apps/src/bin/pravega_retention_checker.rs
- scripts/pravega-retention-checker.sh
Signed-off-by: Luis Liu <luis_liu@dell.com>
> update retention checker and script related

- gst-plugin-pravega/tests/timestampcvt.rs
> timestampcvt: Fix unit test

- python_apps/rtsp-camera-to-pravega.py
This allows the application to remaining running during short segment store server failovers.
> rtsp-camera-to-pravega: Increase buffer-size-mb and health-check-idle-seconds

- pravega-video/src/index.rs
replace linear scan with binary search
> improve index searching performance

- pravega-video-server/src/main.rs
Add check to make sure that files that the binary needs are present at start up.
> Check for Needed Static Files

- docker/build-release.sh
- docker/install-prod-dependencies
- docker/pravega.Dockerfile
Claudio asked me to get #111 up and going. I've lost write permissions to this repo^1 so I had to fork this repo to make a PR.
^1 Intentional, the github.com/pravega org has a new permissions set and I didn't need permissions for it
> Update ubuntu base image

- deepstream/pravega-deepstream.Dockerfile
- deepstream/python_apps/deepstream-pravega-demos/pravega-to-object-detection-to-pravega.py
- deepstream/scripts/build-and-test.sh
- python_apps/lib/gstpravega/__init__.py
- python_apps/lib/gstpravega/health_check.py
- python_apps/lib/gstpravega/util.py
- python_apps/pravega-to-pravega.py
add probe before buffer goes into pravegasink.
Test:
```
GST_PLUGIN_PATH=./target/debug:${GST_PLUGIN_PATH} PROTO_LIB=./target/debug/libnvds_pravega_proto.so ALLOW_CREATE_SCOPE=false GST_DEBUG="WARNING" INPUT_STREAM=examples/camera-claudio-06 MSGAPI_CONFIG_FILE=$HOME/msgapi-config.txt LOG_LEVEL=10 OUTPUT_VIDEO_STREAM=examples/osd-luis-01 pravega_client_tls_cert_path=/etc/ssl/certs/ca-certificates.crt PRAVEGA_CONTROLLER_URI="tls://pravega-controller.kubespray.nautilus-platform-dev.com:443" KEYCLOAK_SERVICE_ACCOUNT_FILE=$HOME/examples.json RUST_LOG="off" HEALTH_CHECK_ENABLED=true  HEALTH_CHECK_IDLE_SECONDS=30 ./deepstream/python_apps/deepstream-pravega-demos/pravega-to-object-detection-to-pravega.py
```
> Add health check for object detection pipeline

- deepstream/deepstream-dev-pod.Dockerfile
- deepstream/pravega-deepstream.Dockerfile
- docker/pravega.Dockerfile
- pravega-video-server/src/main.rs
Replacement PR for https://github.com/pravega/gstreamer-pravega/pull/117.
> Ensure/Check For Static Files Needed At Startup

- deepstream/deepstream-dev-pod.Dockerfile
- deepstream/pravega-deepstream.Dockerfile
- docker/pravega.Dockerfile
- pravega-video-server/src/main.rs
Reverts pravega/gstreamer-pravega#118
Build error:
```
+ docker build -t pravega/gstreamer:pravega-dev-1.3-W11-17-d2b7f68-test --build-arg DEV_IMAGE_NAME=pravega/gstreamer:pravega-dev-1.3-W11-17-d2b7f68 -f ./docker/test.Dockerfile .
Sending build context to Docker daemon   3.67MB
Step 1/5 : ARG DEV_IMAGE_NAME=""
Step 2/5 : FROM ${DEV_IMAGE_NAME}
---> 43d0b45a35b2
Step 3/5 : RUN cargo install cargo2junit
---> Using cache
---> 90a11982475e
Step 4/5 : RUN apt-get update &&     apt-get -y install default-jdk bash net-tools iproute2 &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
---> Running in 19f1c45fa315
Get:1 http://archive.ubuntu.com/ubuntu hirsute InRelease [269 kB]
Get:2 http://security.ubuntu.com/ubuntu hirsute-security InRelease [101 kB]
Err:1 http://archive.ubuntu.com/ubuntu …
```
> Revert "Ensure/Check For Static Files Needed At Startup"

- apps/src/bin/videotestsrc-to-pravega.rs
- deepstream/scripts/camera-to-pravega-blur.sh
- deepstream/scripts/camera-to-pravega-no-blur.sh
- deepstream/scripts/camera-to-pravega-to-screen1.sh
- deepstream/scripts/camera-to-pravega-to-screen2.sh
- deepstream/scripts/camera-to-pravega.sh
- deepstream/scripts/videotestsrc-to-pravega.sh
- gst-plugin-pravega/src/pravegasink/imp.rs
- scripts/audio-to-pravega.sh
- scripts/avtestsrc-to-pravega-1x2.sh
- scripts/avtestsrc-to-pravega-hls.sh
- scripts/avtestsrc-to-pravega-split-no-ts.sh
- scripts/avtestsrc-to-pravega-split.sh
- scripts/avtestsrc-to-pravega.sh
- scripts/benchmark-e2e-latency-camera.sh
- scripts/benchmark-e2e-latency-historical.sh
- scripts/benchmark-e2e-latency-tail.sh
- scripts/benchmark-pravegasink.sh
- scripts/camera-to-pravega-and-screen-then-decode.sh
- scripts/camera-to-pravega-and-screen.sh
- scripts/camera-to-pravega.sh
- scripts/mp4-test4.sh
- scripts/mp4-test5.sh
- scripts/videotestsrc-to-pravega-1x2.sh
- scripts/videotestsrc-to-pravega-b-frames.sh
- scripts/videotestsrc-to-pravega-h264stream.sh
- scripts/videotestsrc-to-pravega-hls.sh
- scripts/videotestsrc-to-pravega-keycloak.sh
- scripts/videotestsrc-to-pravega-live-ts.sh
Other timestamp modes were previously deprecated.
> pravegasink: Change default timestamp-mode to tai

- gst-plugin-pravega/src/pravegasink/imp.rs
In order to detect any stalls writing the index stream, flush the index stream periodically. This will wait for all previous index records to be durably persisted. This happens at the same time as data stream flushes so there is no performance impact expected.
> pravegasink: Periodically flush index writer to detect stalls

- python_apps/rtsp-camera-to-pravega.py
1. do the same as the one for object detection pipeline.
2. no test due to failure to compile when building the current master.
```
error[E0277]: `[&str; 3]` is not an iterator
--> pravega-video-server/src/main.rs:76:17
|
76 |     for file in ["static/gap-5s.mp4", "static/hls-js.js", "templates/player.html"] {
|                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ borrow the array with `&` or call `.iter()` on it to iterate over it
|
= help: the trait `Iterator` is not implemented for `[&str; 3]`
= note: arrays are not iterators, but slices like the following are: `&[1, 2, 3]`
= note: required because of the requirements on the impl of `IntoIterator` for `[&str; 3]`
= note: required by `into_iter`
```
> replace health check with gstpravega lib for the rstp to pravega pipeline

- python_apps/rtsp-camera-to-pravega.py
Reverts pravega/gstreamer-pravega#134
> Revert "replace health check with gstpravega lib for the rstp to pravega pipeline"

- docker/pravega.Dockerfile
- python_apps/lib/gstpravega/health_check.py
- python_apps/lib/gstpravega/util.py
- python_apps/rtsp-camera-to-pravega.py
Fixes: Camera recorder application crashes if health check probe is called before it is initialized
> rtsp-camera-to-pravega-py: Replace health check with gstpravega lib

- k8s/gstreamer-interactive.yaml
- python_apps/rtsp-camera-to-mp4.py
Add rtsp-camera-to-mp4.py script for RTSP testing. This supports several parameters for secure RTSP.
> Add rtsp-camera-to-mp4.py script for RTSP testing

- README.md
> Add a table of contents and additional details to README.md

- pravega-video-server/src/main.rs
allow all origins cors for pravega video server so that grafana pravega video player plugin could comunicate with pravega video server
> Allow all origins cors
